apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio-project
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fanida
  SPRING_DATASOURCE_USERNAME: test
  SPRING_DATASOURCE_PASSWORD: test
  JWT_SECRET: your_jwt_secret_here
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: admin12345