repo_url: "https://github.com/dazinenoamane/devops-portfolio-platform"
repo_branch: "main"
project_dir: "/opt/portfolio-project"

common_packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - apt-transport-https
  - lsb-release
  - software-properties-common

docker_users:
  - ubuntu

kubernetes_version: "1.30"
kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

kubernetes_pod_network_cidr: "192.168.0.0/16"
kubernetes_cni_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/calico.yaml"
kubernetes_cri_socket: "unix:///run/containerd/containerd.sock"

kubernetes_sysctl_config:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
